#!/bin/bash

#always start status indicator script first, run in background
sudo python /home/pi/HeavySwitch/status.py &
#then start the actual switch control script
sudo python /home/pi/HeavySwitch/switch.py
