#!/bin/bash

#always start status indicator script first, run in background
sudo python /home/pi/heavyswitch/scripts/status.py &
#then start the actual switch control script
sudo python /home/pi/heavyswitch/scripts/switch.py
