#!/bin/bash

# this is the bash file that should be called from /etc/rc.local when the pi first starts
# it runs all scripts in the background to prevent the terminal from getting tied up
# it also calls the start up notifier/emailer

# launch power on email notifier
#sudo python /home/pi/heavyswitch/scripts/startup_email.py
sudo python scripts/startup_email.py
# always start status indicator script first, run in background
#sudo python /home/pi/heavyswitch/scripts/status.py &
sudo python scripts/status.py &
# then start the actual switch control script
# cant run in background because of curses?
#sudo python /home/pi/heavyswitch/scripts/switch.py
sudo python scripts/switch.py
